on: [push]
name: Azure APIM deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy ARM template
    - name: Deploy APIM Products
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: att-az204-apim-rg
        template: src/ArmTemplates/Extracted-Templates/apim-unai-products.template.json
        parameters: apimServiceName=ApimAz204Unai

    # Deploy ARM template
    - name: Deploy APIM Products APIs
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: att-az204-apim-rg
        template: src/ArmTemplates/Extracted-Templates//workspaces/APIM-DevOps-Sample/src/ArmTemplates/Extracted-Templates/apim-unai-apis.template.json
        parameters: apimServiceName=ApimAz204Unai

    # Deploy ARM template
    - name: Deploy APIM Products APIs
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: att-az204-apim-rg
        template: src/ArmTemplates/Extracted-Templates/apim-unai-productAPIs.template.json
        parameters: apimServiceName=ApimAz204Unai

      
